#!/usr/bin/env node
'use strict';

const fs = require('fs');
const path = require('path');

const rootDir = path.resolve(__dirname, '..');
const outputPath = path.join(rootDir, 'docs', 'MVP-External-Evidence-Template.md');
const ledgers = [
  {
    name: 'Launch Evidence',
    path: path.join(rootDir, 'docs', 'MVP-Launch-Evidence.json'),
    collectionKey: 'entries',
  },
  {
    name: 'Miniapp Manual QA',
    path: path.join(rootDir, 'docs', 'Miniapp-Manual-QA.json'),
    collectionKey: 'checks',
  },
  {
    name: 'Admin-Web Manual QA',
    path: path.join(rootDir, 'docs', 'Admin-Web-Manual-QA.json'),
    collectionKey: 'checks',
  },
];

const forbiddenData = [
  'real AppID values',
  'openId/unionId',
  'auth tokens or cookies',
  'phone numbers or SMS codes',
  'passwords or private keys',
  'merchant credentials',
  'payment payloads',
  'raw screenshots with personal data',
  'full order/payment/refund identifiers',
];

function fail(message) {
  console.error(`[external-evidence-template] ERROR: ${message}`);
  process.exit(1);
}

function readJson(filePath) {
  try {
    return JSON.parse(fs.readFileSync(filePath, 'utf8'));
  } catch (error) {
    fail(`cannot read ${filePath}: ${error.message}`);
  }
}

function normalizeLine(value) {
  return `${value || ''}`.trim().replace(/\s+/g, ' ');
}

function getItems(ledger) {
  const data = readJson(ledger.path);
  const items = data[ledger.collectionKey];
  if (!Array.isArray(items)) {
    fail(`${ledger.name} ledger must contain array '${ledger.collectionKey}'`);
  }

  return items
    .filter((item) => item.requiredForMvp && item.status !== 'passed' && item.status !== 'waived')
    .sort((left, right) => left.id.localeCompare(right.id));
}

function collectSections() {
  return ledgers.map((ledger) => ({
    ledger,
    items: getItems(ledger),
  }));
}

function renderFieldList(item) {
  const fields = [
    '- Evidence date: `YYYY-MM-DD`',
    '- Environment: `production | approved-staging | WeChat preview | real device | local devtools`',
    '- Operator: `<role label or reviewer initials>`',
    '- Route/API: `<route, page, or API alias>`',
    '- Sanitized resource alias: `<room/order/payment/refund/admin alias or id suffix only>`',
    '- Result: `passed | failed | waived request`',
    '- Evidence summary: `<short non-secret summary of what was observed>`',
    '- Recovery or rollback: `<restored final status, no mutation, or accepted change>`',
    '- Follow-up: `<remaining action or none>`',
  ];

  if (item.id.includes('PAYMENT') || item.id.includes('REFUND')) {
    fields.splice(2, 0, '- Approval note: `<explicit user approval before real payment/refund>`');
    fields.splice(7, 0, '- Amount band: `<low-value / test amount band only>`');
  }

  if (item.id.includes('8080') || item.id.includes('HARDENING')) {
    fields.splice(4, 0, '- Security rule summary: `<security group/firewall rule summary, no console secrets>`');
  }

  if (item.id.includes('DEPLOYED')) {
    fields.splice(4, 0, '- Workflow evidence: `<workflow run id/url, commit sha, target, smoke result>`');
  }

  return fields.join('\n');
}

function renderItem(item) {
  const lines = [
    `<!-- template:${item.id} -->`,
    `### ${item.id}`,
    '',
    `- Status now: \`${item.status}\``,
    `- Area: ${normalizeLine(item.area) || 'n/a'}`,
    item.route ? `- Route: ${normalizeLine(item.route)}` : null,
    `- Requirement: ${normalizeLine(item.requirement)}`,
    Array.isArray(item.relatedApis) && item.relatedApis.length
      ? `- Related APIs/capabilities: ${item.relatedApis.map((api) => `\`${api}\``).join(', ')}`
      : null,
    `- Current evidence: ${normalizeLine(item.evidence)}`,
    `- Next action: ${normalizeLine(item.nextAction)}`,
    '',
    'Suggested sanitized evidence entry:',
    '',
    renderFieldList(item),
    '',
    'Ledger update reminder:',
    '',
    '- Change `status` only after the evidence above is actually available.',
    '- Use `waived` only with explicit user acceptance and reason.',
    '- Keep `evidence` at least one compact sentence with non-secret proof.',
    '',
  ];

  return lines.filter((line) => line !== null).join('\n');
}

function renderTemplate(sections) {
  const unresolvedTotal = sections.reduce((sum, section) => sum + section.items.length, 0);
  const lines = [
    '# MVP External Evidence Template',
    '',
    '> Generated by `node scripts/generate_mvp_external_evidence_template.js`.',
    '> Fill this template during external QA, then transfer sanitized evidence',
    '> into the JSON ledgers. Do not commit raw screenshots or secrets.',
    '',
    '## Summary',
    '',
    `- Generated at: 2026-06-02`,
    `- Unresolved required items: ${unresolvedTotal}`,
    '- Source ledgers:',
    '  - `docs/MVP-Launch-Evidence.json`',
    '  - `docs/Miniapp-Manual-QA.json`',
    '  - `docs/Admin-Web-Manual-QA.json`',
    '',
    '## Safety Rules',
    '',
    'Do not record or commit:',
    '',
    ...forbiddenData.map((item) => `- ${item}`),
    '',
    'Record only sanitized aliases, masked suffixes, date/environment/result,',
    'and a short operator note. Real payment, real refund, production data',
    'mutation, security-group/firewall changes, `push main`, and',
    '`workflow_dispatch` require explicit user approval first.',
    '',
  ];

  for (const section of sections) {
    lines.push(`## ${section.ledger.name}`, '');
    if (!section.items.length) {
      lines.push('All required items in this ledger are passed or waived.', '');
      continue;
    }

    for (const item of section.items) {
      lines.push(renderItem(item));
    }
  }

  lines.push(
    '## Final Checks',
    '',
    'After transferring sanitized evidence into the JSON ledgers, run:',
    '',
    '```bash',
    'node scripts/check_mvp_launch_evidence.js',
    'node scripts/check_miniapp_manual_qa.js',
    'node scripts/check_admin_web_manual_qa.js',
    'node scripts/check_mvp_closeout_readiness.js',
    '```',
    '',
    'Before declaring MVP complete, strict mode must pass:',
    '',
    '```bash',
    'node scripts/check_mvp_launch_evidence.js --strict',
    'node scripts/check_miniapp_manual_qa.js --strict',
    'node scripts/check_admin_web_manual_qa.js --strict',
    'node scripts/check_mvp_closeout_readiness.js --strict',
    '```',
    '',
  );

  return `${lines.join('\n')}\n`;
}

function main() {
  const sections = collectSections();
  const content = renderTemplate(sections);
  fs.writeFileSync(outputPath, content, 'utf8');
  const unresolvedTotal = sections.reduce((sum, section) => sum + section.items.length, 0);
  console.log(`[external-evidence-template] wrote docs/MVP-External-Evidence-Template.md with ${unresolvedTotal} unresolved required item(s)`);
}

main();
